[project]
name = "util-scripts"
readme = "README.md"
requires-python = ">= 3.13"
dependencies = [
  "ffmpeg-normalize",
  "fontra",
  "nicegui",
  "pydantic",
  "pydantic-extra-types",
  "pytimeparse2",
  "pywebview",
  "typed-ffmpeg",
]