[project]
name = "util-scripts"
requires-python = ">= 3.14"
dependencies = [
  "ffmpeg-normalize",
  "fontra",
  "nicegui",
  "pydantic",
  "pydantic-extra-types",
  "pytimeparse2",
  # "pywebview",
  "typed-ffmpeg",
]
